from crud.calendar import *
from crud.club import *
from crud.coach import *
from crud.game import *
from crud.game_pve import *
from crud.league import *
from crud.offer import *
from crud.player import *
from crud.save import *
from crud.target_player import *
from crud.user import *
from crud.user_finance import *
