from schemas.calendar import *
from schemas.game import *
from schemas.player import *
from schemas.coach import *
from schemas.club import *
from schemas.league import *
from schemas.save import *
from schemas.game_pve import *
from schemas.user import *
from schemas.targetplayer import *
from schemas.offer import *
