from modules.generate_app.player_generator import PlayerGenerator
from modules.generate_app.coach_generator import CoachGenerator
from modules.generate_app.calendar_generator import CalendarGenerator
from modules.generate_app.save_generator import SaveGenerator
from modules.generate_app.league_generator import LeagueGenerator
from modules.generate_app.league_system_generator import LeagueSystemGenerator
