from modules.generate_app.player_generator import PlayerGenerator
from modules.generate_app.coach_generator import CoachGenerator
from modules.generate_app.calendar_generator import CalendarGenerator
from modules.generate_app.save_generator import SaveGenerator
from modules.generate_app.league_generator import LeagueGenerator
from modules.generate_app.club_generator import ClubGenerator
from modules.generate_app.game_pve_generator import GamePvEGenerator
